### ISSUE TITLE
LUA Error in 11.0.2

### ISSUE THREAD

**Issue by Andf** [romdeau23/wow-enchant-me#3]
Hello!

Receving the following error with latest patch, addon not working anymore.

18x ...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:351: attempt to call method 'GetVariableType' (a nil value)
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:351: in function `CreateCheckboxInitializer'
[string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:375: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:374>
[string "=(tail call)"]: ?
[string "@EnchantMe/modules/settings.lua"]:13: in function `init'
[string "@EnchantMe/lib/module.lua"]:15: in function `listener'
[string "@EnchantMe/lib/event.lua"]:37: in function <EnchantMe/lib/event.lua:33>

Locals:
setting = <table> {
 order = 13
 ID = 13
 name = "Enchant Me"
 subcategories = <table> {
 }
}
options = nil
tooltip = "Ignore missing Shadowed Belt Clasp
(as it is usually very expensive and only gives a small amount of stamina)"
(*temporary) = nil
(*temporary) = <table> {
 order = 13
 ID = 13
 name = "Enchant Me"
 subcategories = <table> {
 }
}
(*temporary) = "attempt to call method 'GetVariableType' (a nil value)"

**Comment by romdeau23** [comment]
Hey, this was just fixed in 1.3.7 (75d97eb7a4d2f7cde654d9f7639dd6c42e7583cc).

**Comment by Andf** [comment]
Many thanks for the quick fix!
